[package]
name = "librespot-protocol"
version = "0.1.3"
authors = ["Paul Li√©tar <paul@lietar.net>"]
build = "build.rs"
description="The protobuf logic for communicating with Spotify servers"
license="MIT"
edition = "2018"

[dependencies]
protobuf = "~2.14.0"

[build-dependencies]
protobuf-codegen-pure = "~2.14.0"
protobuf-codegen = "~2.14.0"
glob = "0.3.0"
