[package]
name = "librespot-protocol"
version = "0.3.1"
authors = ["Paul Li√©tar <paul@lietar.net>"]
build = "build.rs"
description = "The protobuf logic for communicating with Spotify servers"
license = "MIT"
repository = "https://github.com/librespot-org/librespot"
edition = "2018"

[dependencies]
protobuf = "2.25"

[build-dependencies]
protobuf-codegen-pure = "2.25"
glob = "0.3.0"
