[package]
name = "librespot-connect"
version = "0.5.0-dev"
rust-version = "1.74"
authors = ["Paul Lietar <paul@lietar.net>"]
description = "The discovery and Spotify Connect logic for librespot"
license = "MIT"
repository = "https://github.com/librespot-org/librespot"
edition = "2021"

[dependencies]
form_urlencoded = "1.0"
futures-util = "0.3"
log = "0.4"
protobuf = "3"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "parking_lot", "sync"] }
tokio-stream = "0.1"

[dependencies.librespot-core]
path = "../core"
version = "0.5.0-dev"

[dependencies.librespot-playback]
path = "../playback"
version = "0.5.0-dev"

[dependencies.librespot-protocol]
path = "../protocol"
version = "0.5.0-dev"
