[package]
name = "librespot-connect"
version = "0.1.6"
authors = ["Paul Lietar <paul@lietar.net>"]
description = "The discovery and Spotify Connect logic for librespot"
license = "MIT"
repository = "https://github.com/librespot-org/librespot"
edition = "2018"

[dependencies.librespot-core]
path = "../core"
version = "0.1.6"
[dependencies.librespot-playback]
path = "../playback"
version = "0.1.6"
[dependencies.librespot-protocol]
path = "../protocol"
version = "0.1.6"

[dependencies]
aes-ctr = "0.6"
base64 = "0.13"
block-modes = "0.7"
futures = "0.1"
hmac = "0.10"
hyper = "0.11"
log = "0.4"
num-bigint = "0.3"
protobuf = "~2.14.0"
rand = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha-1 = "0.9"
tokio-core = "0.1"
url = "1.7"

dns-sd = { version = "0.1.3", optional = true }
libmdns = { version = "0.2.7", optional = true }

[features]
default = ["libmdns"]
with-dns-sd = ["dns-sd"]
