[package]
name = "librespot-connect"
version = "0.6.0-dev"
rust-version.workspace = true
authors = ["Paul Lietar <paul@lietar.net>"]
description = "The discovery and Spotify Connect logic for librespot"
license = "MIT"
repository = "https://github.com/librespot-org/librespot"
edition = "2021"

[dependencies]
futures-util = "0.3"
log = "0.4"
protobuf = "3.7"
rand = { version = "0.9", default-features = false, features = ["small_rng"] }
serde_json = "1.0"
thiserror = "2"
tokio = { version = "1", features = ["macros", "parking_lot", "sync"] }
tokio-stream = "0.1"
uuid = { version = "1.18", features = ["v4"] }

[dependencies.librespot-core]
path = "../core"
version = "0.6.0-dev"

[dependencies.librespot-playback]
path = "../playback"
version = "0.6.0-dev"

[dependencies.librespot-protocol]
path = "../protocol"
version = "0.6.0-dev"
