[package]
name = "librespot-connect"
version = "0.1.6"
authors = ["Paul Lietar <paul@lietar.net>"]
description = "The discovery and Spotify Connect logic for librespot"
license = "MIT"
repository = "https://github.com/librespot-org/librespot"
edition = "2018"

[dependencies]
aes-ctr = "0.6"
base64 = "0.13"
block-modes = "0.7"
form_urlencoded = "1.0"
futures-core = "0.3"
futures-util = { version = "0.3", default_features = false }
hmac = "0.10"
hyper = { version = "0.14", features = ["server", "http1", "tcp"] }
log = "0.4"
protobuf = "~2.14.0"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha-1 = "0.9"
tokio = { version = "1.0", features = ["macros", "rt", "sync"] }
tokio-stream = { version = "0.1" }
url = "2.1"

dns-sd = { version = "0.1.3", optional = true }
libmdns = { version = "0.6", optional = true }

[dependencies.librespot-core]
path = "../core"
version = "0.1.6"

[dependencies.librespot-playback]
path = "../playback"
version = "0.1.6"

[dependencies.librespot-protocol]
path = "../protocol"
version = "0.1.6"

[features]
with-libmdns = ["libmdns"]
with-dns-sd = ["dns-sd"]

default = ["with-libmdns"]
